sudo: required
language: python
python:
  - '3.6'

services:
  - docker


# use matrix to parallelize tests
matrix:
  fast_finish: true
  include:
    # - name: "Aether CORE tests (Kernel, Client, UI, ODK and CouchDB-Sync)"
    #   stage: test
    #   env: 'TEST_MODE=all'

    # split containers one by one
    # - name: "Aether Kernel tests"
    #   stage: test
    #   env: 'TEST_MODE=kernel'

    # - name: "Aether Client tests"
    #   stage: test
    #   env: 'TEST_MODE=client'

    # - name: "Aether ODK module tests"
    #   stage: test
    #   env: 'TEST_MODE=odk'

    # - name: "Aether CouchDB-Sync module tests"
    #   stage: test
    #   env: 'TEST_MODE=couchdb-sync'

    # - name: "Aether UI tests"
    #   stage: test
    #   env: 'TEST_MODE=ui'

    # - name: "Integration tests (Kernel with Kakfa/Zookeeper and Producer)"
    #   stage: test
    #   env: 'TEST_MODE=integration'

    #  - name: "Kubernetes tests (Kernel and ODK)"
    #    stage: test
    #    env: 'TEST_MODE=kubernetes'

    # execute only to deploy
    - name: "Aether release"
      stage: deploy
      script: ./scripts/release.sh

install: true

before_script:
  - ./scripts/generate-docker-compose-credentials.sh > .env

script:
  - ./scripts/test_travis.sh $TEST_MODE

after_script:
  - ./scripts/kill_all.sh

after_failure:
  - ./scripts/test_travis_failure.sh $TEST_MODE

# TODO: move this secured global env var to Travis settings
env:
  - secure: joWZmJ2gh3J7Pio9QBsf0DOoGxanJV4osIoNo5YjlPDfLfXtEnpUMijP/YJikOo/pExTbvTs/90G0aC+Z00CkjgJxMXHESwg8+4VpPnSP0qn23rkY7+Wzm0N7Xn1Ylv9FkPxlJMYJ5f/EPksNZSbo97HMkvA+rV2vbTAIV8NhTAoCjDexTdsBVBvg6YOgaipf9HouxDmuGcd6kRSIEU7ZdHz21WTWd46yB6jzbyfI675Vaz42UOLVH2xsW3xNCor7hkiBtlH20DhKgDF+oQXXyi5ySIf/7rWR6isZMFMZWg264ytbNQyFiFytKCsafPy6JSnmZ6YVnuDbb2ibtlcBd4wmDOGlF30uVdJxpqq8+l4xOaot627CjI4nvcL48/E+S09MTJfZmlEDHy79vXRtZiQzPgwhBD+MA93QooiQaITOrm6rXc3PvnZB0HNjX88qzbrdT58Yh0rO9I0LcnW/VVR9NV3mw5sWnx1KEDvQowNtXkXTuEPzetjw+wK6ogLjiEH49rybbbHYuO24e07ldFySWkiB6UgFqu38XTZ+QwPbIFK2NYGfRuxTvTqSdiP4yvpz6BoiJLh5ftgzTD17rCYS25om1YmYHv7TyhB87UqiM1kk8gZ7GV19kim4B416nlDUo/VbYloUx0RmpPa/jyN56lhOvYBxa/3SwkzrDY=
  global:
    secure: PmbhrEFpSypsToBPSTPOxPPgzr6YM+kpFutHn9WJm5VNicukhstPSxo5q4nZ6wrHL+8C3GsJjVMA+YEg2r8kU9w/uEFwJYn4irEWivKwAdglhZLIyfXmhPbBSHoPvDFfAp7mIvX57QOuKvw/ZA22zgsFN3Di9b5VPN6khYwALpAsEJb9qj8UewPfFbcJBhR9l01ZTOcnN27vT6rlCA+WKleViYjMvO8Ru+1H/sOSFEJYA9SRroa2fc8N249tM7MNt9NmDBilOSai98TujHMcgvPM6n1D0YFjqAm6KyvQpW3QdNF5mfhzJVFM48SpsQpzE2xMDeU+NBtYmUV1BgdJcv56qC88NUtOxtK3oQ3NN2l5XyJnLLM3R5zGHyCZ1AOc8w0y8Bn7yYElTwMXAMnsNzuWE+fXR7MJjVIoDkvgmAfnDvDpOwPNC2P/6DDu5doQvdkM//hNGvxlbGnYsoTLBKuFWwy84YXs3ACSFHtKUMf+/yBsVWJ3Nqe/YCMt1052sd7cumjcgyCQNu0xNv6DRoPqNTnqmWzHHROp8DShGEGG+6k8QD2l14thedV7o/esSKSYBKlkcDt1+4F+VKGYKq5jEtMu8dLELoZ1ldZLWNmyYi81FkA+c5BXHOh+ixTkoamqZ1pkyCF0Q82V9wGkVZh+BJxwYb+9tcWy8Yw/llw=
